services:
  app:
    build: .
    command: bash -c "cd src && uvicorn api:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./src:/app/src
      - ./dvc.yaml:/app/dvc.yaml
      - ./params.yaml:/app/params.yaml
    ports:
      - "8000:8000"
  
  pipeline:
    build: .
    command: bash -c "dvc repro"
    volumes:
    - ./data:/app/data
    - ./outputs:/app/outputs
    - ./src:/app/src
    - ./dvc.yaml:/app/dvc.yaml
    - ./params.yaml:/app/params.yaml
  